pipeline:
  build:
    image: nixos/nix
    commands:
      - nix develop --command bash -c "
          npm ci &&
          npm run build
        "

  deploy:
    image: alpine/git
    commands:
      - git config --global user.name 'CI Deploy Bot'
      - git config --global user.email 'ci@codeberg.org'

      - git clone --depth 1 --branch pages $CI_REPO_CLONE_URL pages_branch
      - rm -rf pages_branch/*
      - cp -r build/* pages_branch/

      - cd pages_branch
      - git add .
      - git commit -m 'Deploy: $CI_COMMIT_MESSAGE' || true
      - git push origin pages
